travis:
  secure:
    BINSTAR_TOKEN: dOwhiQNw8r2nt0PwFdQQUKLH6fRWL9/Qlf6/hbH6QqdEQgNrc6t5cEldeEpmnSbwu2gCq7Z5sGg5El3Y+Ky2FGm/tdT6zR9L8njkeFbz1I5ttMlHzBEMIazbbJjOoqCB3WG54ZhgqcVzC9nP2Rp8+wu1f5iOcDMnSh4LE4PlPXdr8xZXxWwR7AKd+DEOXk2HU8F0SarFm9WCd4CLU6gIaP57KEFkELDQgx2RF+W2moh2x+H5CYh0ckbF1ygGCXiYmtlthJyLiVrs9DQlOiEh9oZkNPnxzZLEs1VCX/i9JSmAqtRtNoUhIfc44ckdabZlZ6AEiw1b6fg1ruMkCrO2e69WS3V/ncSBTaZT0jmtAWl6w5iaJVUCjWSMjtC52pWcXCr0wy1p1+PM+FJuKJctAg36qZigsR8V2iMr4J5vByzsI6TX5yeJMrZCv55Vz+dAK94ZPj6WXOzebOCsTx6M/QK6t++rE68I95xZW9FIYbXrJgpsrX5Jzrjx65YtvBvVpSvq+BZQqT+i9srSoyaifYYinxNWatpqILTF8qwcCLVPJ6KIwFgSQZoEXfkhr0MX6Ctn25gYGUy37cgJGpXI//ay+1vNjusT6Yea3WtI6hx9SCB7g6pAtEqYaJtIzDniVMJgBGED21Z87BkjVzHvQrhbvc0f+kKYCJWQ+Uhnp/g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
